src/blog/urls.py
from django.urls import path
from .views import BlogList, blog_add, blog_detail, blog_update, blog_delete, like
from django.conf import settings
from django.conf.urls.static import static

app_name = "blog"
urlpatterns = [
    path('', BlogList.as_view(), name='main_page'),
    path("create/",blog_add, name="add"),
    path("<str:slug>/",blog_detail, name="detail"),
    path("<str:slug>/update/",blog_update, name="update"),
    path("<str:slug>/delete/",blog_delete, name="delete"),
    path("<str:slug>/like/",like, name="like"),
]
if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/cblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('users.urls')),
]
# + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
      integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'blog/main.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Kaisei+Opti:wght@700&display=swap"
      rel="stylesheet"
    />
    <title>Blog Project</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container mt-5 pt-3">
      {% if messages %} {% for message in messages %}

      <div class="alert alert-{{ message.tags }}">{{ message }}</div>

      {% endfor %} {% endif %} {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://kit.fontawesome.com/74c8282b8a.js"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'js/timeout.js' %}"></script>
    <script src="{% static 'js/hover.js' %}"></script>

  </body>
</html>

src/templates/navbar.html
{% load static %}
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-secondary">
    <button
      class="navbar-toggler navbar-toggler-right"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarCollapse"
      aria-controls="navbarCollapse"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'blog:main_page' %}">
      <img style="width: 2rem;" src="{% static 'images/logo.svg' %}" alt="static 'images/logo.svg' " />
      Blog
    </a>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'blog:main_page' %}">Home</a>
        </li>
        {% if request.user.is_authenticated %} 
        {% if request.user.is_superuser%}

        <li class="nav-item active">
          <a class="nav-link" href="/admin">Admin</a>
        </li>
        {% endif %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'about' %}">About</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'profile' %}">Profile</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'blog:add' %}">New</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}

        <li class="nav-item active">
          <a class="nav-link" href="{% url 'about' %}">About</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'register' %}">Register</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>