src/blog/urls.py
from django.urls import path
from .views import BlogList, blog_add, blog_detail, blog_update, blog_delete, like
from django.conf import settings
from django.conf.urls.static import static

app_name = "blog"
urlpatterns = [
    path('', BlogList.as_view(), name='main_page'),
    path("create/",blog_add, name="add"),
    path("<str:slug>/",blog_detail, name="detail"),
    path("<str:slug>/update/",blog_update, name="update"),
    path("<str:slug>/delete/",blog_delete, name="delete"),
    path("<str:slug>/like/",like, name="like"),
]
if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/cblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('users.urls')),
]
# + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


def user_directory_path(instance, filename):
    return 'blog/{0}/{1}'.format(instance.author.id, filename)
    #create folder for every id
class Category(models.Model):
    name = models.CharField(max_length=100)
    
    class Meta:
        verbose_name_plural = "Categories"
        
    def __str__(self):
        return self.name

class Blog(models.Model):
    # OPTIONS = (
    #     ('d', 'Draft'),
    #     ('p', 'Published')
    # )
  
    title = models.CharField(max_length=100)    
    text = models.TextField()
    image = models.ImageField(upload_to=user_directory_path, default='django.jpg')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, blank=True, null=True)
    # publish_date = models.DateTimeField(auto_now_add=True)
    # last_updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # status = models.CharField(max_length=10, choices=OPTIONS, default='d')
    slug = models.SlugField(blank=True)
    created_date = models.DateTimeField(
        default=timezone.now)
    def __str__(self):
        return self.title
    
    
    def comment_count(self):
        return self.comment_set.all().count()
    
    def view_count(self):
        return self.blogview_set.all().count()
    
    def like_count(self):
        return self.like_set.all().count()
    
    def comments(self):
        return self.comment_set.all()

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comment")
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    time_stamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    
    def __str__(self):
        return self.user.username
    
class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username
    
class BlogView(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    time_stamp = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.user.username
    

src/blog/forms.py
from django import forms
from .models import Blog, Comment, Category

class BlogForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label="Select Category")


    class Meta:
        model = Blog
        widgets = {
            'text': forms.Textarea(attrs={'rows':'5', 'cols': '40'}),
        }
        fields = (
            'title',
            'text',
            'image',
            'category',
        )
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        widgets = {
            'content': forms.Textarea(attrs={'rows':'5', 'cols': '40'}),
        }
        fields = ('content',)
        

src/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from .models import Blog, Like, BlogView, Comment
from .forms import BlogForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.generic import ListView

class BlogList(ListView):
    model = Blog
    template_name = "blog/main_page.html"
    context_object_name = 'blogs'

@login_required()
def blog_add(request):
    # form = BlogForm(request.POST or None, request.FILES or None)
    form = BlogForm()
    if request.method == "POST":
        form = BlogForm(request.POST, request.FILES)
        # print(request.FILES)
        if form.is_valid():
            blog = form.save(commit=False)
            blog.author = request.user
            blog.save()
            messages.success(request, "Blog created successfully!")
            return redirect("blog:main_page")
    context = {
        'form' : form
    }
    return render (request, "blog/blog_add.html", context)

def blog_detail(request, slug):
    form = CommentForm()
    obj = get_object_or_404(Blog, slug=slug)
    if request.user.is_authenticated:
        BlogView.objects.get_or_create(user=request.user, blog=obj)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid:
            comment = form.save(commit=False)
            comment.user = request.user
            comment.blog = obj
            comment.save()
            return redirect("blog:detail", slug=slug)
    context = {
        'object' : obj,
        "form" : form,
    }
    return render(request, "blog/blog_detail.html", context)

@login_required()
def blog_update(request, slug):
    obj = get_object_or_404(Blog, slug=slug)
    form = BlogForm(request.POST or None, request.FILES or None, instance=obj)
    if request.user.id != obj.author.id:
        # return HttpResponse("You are not authorized!")
        messages.warning(request, "You are not an author of this blog!")
        return redirect("blog:main_page")
    if form.is_valid():
        form.save()
        messages.success(request, "Blog updated !!")
        return redirect("blog:main_page")
    context = {
        "object" : obj,
        "form" : form
    }
    return render(request, "blog/blog_update.html", context)

@login_required()
def blog_delete(request, slug):
    obj = get_object_or_404(Blog, slug=slug)
    if request.user.id != obj.author.id:
        # return HttpResponse("You are not authorized!")
        messages.warning(request, "You are not an author of this blog!")
        return redirect("blog:main_page")
    if request.method == "POST":
        obj.delete()
        messages.success(request, "Blog deleted !!")
        return redirect("blog:main_page")
    
    context = {
        "object" : obj
    }
    return render(request, "blog/blog_delete.html", context)

@login_required()
def like(request, slug):
    if request.method == "POST":
        obj = get_object_or_404(Blog, slug=slug)
        like_qs = Like.objects.filter(user=request.user, blog=obj)
        if like_qs.exists():
            like_qs[0].delete()
        else:
            Like.objects.create(user=request.user, blog=obj)
        return redirect("blog:detail", slug=slug)
    return redirect("blog:detail", slug=slug)

src/blog/templates/blog/blog_add.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block content %}
<div class="row">
  <div class="col-md-6 offset-md-3">
    <form method="POST" enctype="multipart/form-data">   
      {% csrf_token %} {{form|crispy}}
      <br />
      <button type="submit" class="btn btn-outline-info btn-block">Add</button>
    </form>
  </div>
</div>

{% endblock content %}

    

src/blog/templates/blog/blog_delete.html
{% extends 'base.html' %} {% load static %}
{% block content %}
<div class="row mt-5 mx-auto">
  <div class="col-md-6 mx-auto">
    <div class="card card-body bg-light border border-secondary border-3 rounded-3">
      <p>Are you sure you want to delete <strong>"{{object}}"</strong> ?</p>
      <form action=" " method="POST">
        {% csrf_token %}
        <div class="d-grid gap-2 mx-auto">
          <a class="btn btn-info" href="{% url 'blog:main_page' %}"
            >Cancel</a
          >
          <input
            class="btn btn-danger"
            type="submit"
            name="Confirm"
            value="Delete"
          />
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

src/blog/templates/blog/blog_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="card mb-3 p-2 border-info">
    <div class="row g-0">
      <div class="col-md-6">
        <img src="{{ object.image.url }}" class="img-fluid rounded-start" alt="blog_image" 
        style="object-fit: fill; width: 30rem; height: 20rem; border-radius: 4px;">
        <div class="card-body">
            <h5 class="card-title">{{ object.title }}</h5>
            <hr>
            <p class="card-text">{{ object.text }}.</p>
            
            
        </div>
      </div>
      <div class="col-md-6">
        <div class="m-3 pb-3 d-flex justify-content-evenly">
            <span class="text-secondary"><i class="far fa-comment fa-3x "></i></i> {{ object.comment_count }}</span>
            <span class="text-info"><i class="fas fa-eye ml-3 fa-3x"></i> {{ object.view_count }}</span>
            <span class="text-danger" id="heart"><i class="fab fa-gratipay ml-3 fa-3x"></i> {{ object.like_count }}</span>
        </div>
        <div>
            <form action="{% url 'blog:like' object.slug %}" method="POST">

                {% csrf_token %}
                <input type="hidden" name="blog">
                <input type="hidden" name="user">

                <button type="submit" class="btn btn-outline-primary btn-lg btn-block"><i class="fas fa-thumbs-up lg"> Like </i></i></button>
            </form>
            <hr>
            <!-- {% if user.is_authenticated %} -->
            <h4>Leave a comment below</h4>
            <form action="" method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <button class="btn btn-secondary btn-block">SEND</button>
            </form>
            <hr>
            <h4>Comments</h4>
            {% for comment in object.comments %}
            <div>
                <p>
                    <small><b>Comment by {{comment.user}}</b></small>
                     - 
                    <small>{{ comment.time_stamp|timesince }} ago.
                    </small>
                </p>
                <p>{{ comment.content }}</p>
            </div>
            <hr>
            {% endfor %}
            <!-- {% else %} -->
            <!-- <a href="#" class="btn btn-primary btn-block">Login to comment</a> -->
            <!-- {% endif %} -->
        
        </div>

      </div>

        <div class="p-2">
        {% if user.id == object.author.id %}
        <a href="{% url 'blog:update' object.slug %}" class="btn btn-info btn-block">Edit</a>
        <a href="{% url 'blog:delete' object.slug %}" class="btn btn-danger btn-block">Delete</a>
        {% endif %}
        </div>
    </div>
</div>

{% endblock content %}

src/blog/templates/blog/blog_update.html
{% extends 'base.html' %} {% load crispy_forms_tags %}

{% block content %}
<div class="row">
  <div class="col-md-6 offset-md-3">
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %} {{form|crispy}}
      <br />
      <button type="submit" class="btn btn-outline-info btn-block">Update</button>
    </form>
  </div>
</div>

{% endblock content %}

    

src/blog/templates/blog/details.html
{% extends 'users/base.html' %} {% block content %}
<h1>Details Page</h1>
{% if request.user.is_authenticated %}
<h2>Welcome {{request.user}}!</h2>
{% else %}
<h2>There will be detail of the blog</h2>
{% endif %} {% endblock content %}

src/blog/templates/blog/main_page.html
{% extends 'base.html' %} {% block content %}
<div class="container">
    <div class="row my-2 mt-5">
  {% for obj in object_list %}
  <div class="col-12 col-sm-6 col-md-4 my-3">
    <div class="card shadow mb-5 border border-secondary bg-light rounded-top" style="max-width: 20rem; min-width: 14rem;">
        <img src="{{ obj.image.url }}" class="card-img-top" alt="blog_image" style="height: 14rem;"/>
        <!-- <h5 class="card-header text-center">{{ obj.category }}</h5> -->
      <div class="card-body p-4">
        <h5 class="card-title text-center">
          <a href="{% url 'blog:detail' obj.slug %}">{{obj.title}}</a>
        </h5>
        <p class="card-text text-center">{{obj.text|truncatechars:20}}</p>

        <p class="card-text d-flex justify-content-evenly ">
          <span class="text-secondary"><i class="far fa-comment fa-lg"></i> {{ obj.comment_count }}</span>
          <span class="text-info"><i class="fas fa-eye ml-3 fa-lg"></i> {{ obj.view_count }}</span>
          <span class="text-danger"><i class="fab fa-gratipay ml-3 fa-lg"></i> {{ obj.like_count }}</spanS>
        </p>
        <div class="card-footer p-0 m-0">
        <p class="card-text text-center">
          <small class="text-muted"><i class="far fa-clock"></i> Created {{obj.created_date|timesince}} ago. </small>
        </p>
      </div>
    </div>
    </div>
  </div>

  {% endfor %}
</div>
</div>
{% endblock content %}